openapi: 3.0.2
info:
  title: Example API
  description: This is the example API
  version: '0.1'
servers:
  - url: 'http://localhost:8080/example/api'
tags:
  - name: Example
    description: Operations with the example API
paths:
  /start:
    post:
      summary: Starts the solver
      tags:
        - Example
      operationId: startSolver
      requestBody:
        description: Lorum Ipsum
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleProblemInstance'
      responses:
        '201':
          description: Solver started
        '400':
          description: Data validation error
  /result:
    get:
      summary: Returns a solution
      tags:
        - Example
      operationId: getResult
      responses:
        '200':
          description: Generated solution
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExampleTask'
        '404':
          description: Result not found
components:
  schemas:
    ExampleTask:
      type: object
      required:
        - duration
        - isStrict
        - isHeavy
      properties:
        assignedEmployeeId:
          type: string
        duration:
          type: integer
        isStrict:
          type: boolean
        isHeavy:
          type: boolean
        priority:
          type: boolean
    ExampleProblemInstance:
      type: object
      title: Example Problem Instance
      description: This is an example problem instance. Write descripion for the class here
      required:
        - tasks
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/ExampleTask'
