openapi: 3.0.2
tags:
  - name: Example
    description: Operations with the example API
info:
  title: Example API
  version: '0.1'
  description: >
    This is the example API
paths:
  /start_solver:
    post:
      $ref: "./paths/startSolver.yml"
  /result:
    get:
      $ref: "./paths/getResult.yml"

components:
  schemas:
    $ref: "./schemas.yml"
